SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE USERS IF EXISTS;
CREATE TABLE USERS (
userId INTEGER IDENTITY,
login VARCHAR(1024) NOT NULL,
hash VARCHAR(1024) NOT NULL,
salt INTEGER NOT NULL,
n INTEGER NOT NULL,
);