SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE MALFUNCTION IF EXISTS;
CREATE TABLE MALFUNCTION (
malfunctionId INTEGER IDENTITY,
name VARCHAR(255) NOT NULL,
auto VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
costRepair INTEGER,
costService INTEGER,
additionalExpenses INTEGER
);