SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE APPLICATION IF EXISTS;
CREATE TABLE APPLICATION (
applicationId INTEGER IDENTITY,
createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);