SET DATABASE SQL SYNTAX ORA TRUE;
DROP TABLE USERS IF EXISTS;
CREATE TABLE USERS (
applicationId INTEGER IDENTITY,
login VARCHAR(255) NOT NULL,
passHash VARCHAR(255) NOT NULL,
salt INTEGER NOT NULL,
);